// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile() {
  return window['go']['main']['App']['AddFile']();
}

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckVaultExists() {
  return window['go']['main']['App']['CheckVaultExists']();
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DisableTOTP() {
  return window['go']['main']['App']['DisableTOTP']();
}

export function EnableTOTP(arg1, arg2) {
  return window['go']['main']['App']['EnableTOTP'](arg1, arg2);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function ExportFile(arg1) {
  return window['go']['main']['App']['ExportFile'](arg1);
}

export function ExportFileForced(arg1) {
  return window['go']['main']['App']['ExportFileForced'](arg1);
}

export function ExtractFromImage() {
  return window['go']['main']['App']['ExtractFromImage']();
}

export function GetFileTamperDetails(arg1) {
  return window['go']['main']['App']['GetFileTamperDetails'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function HideInImage(arg1, arg2) {
  return window['go']['main']['App']['HideInImage'](arg1, arg2);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function IsReadOnly() {
  return window['go']['main']['App']['IsReadOnly']();
}

export function IsTOTPEnabled() {
  return window['go']['main']['App']['IsTOTPEnabled']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function PreviewHideInImage(arg1, arg2) {
  return window['go']['main']['App']['PreviewHideInImage'](arg1, arg2);
}

export function ResetPasswordWithRecovery(arg1, arg2) {
  return window['go']['main']['App']['ResetPasswordWithRecovery'](arg1, arg2);
}

export function RestoreFromBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromBackup'](arg1, arg2);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SetupTOTP() {
  return window['go']['main']['App']['SetupTOTP']();
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2);
}

export function UnlockVaultReadOnly(arg1) {
  return window['go']['main']['App']['UnlockVaultReadOnly'](arg1);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}

export function ValidateRecoveryKey(arg1) {
  return window['go']['main']['App']['ValidateRecoveryKey'](arg1);
}

export function VerifyFile(arg1) {
  return window['go']['main']['App']['VerifyFile'](arg1);
}
