// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile():Promise<main.Response>;

export function AddNote(arg1:string,arg2:string,arg3:Array<string>):Promise<main.Response>;

export function ChangePassword(arg1:string,arg2:string):Promise<main.Response>;

export function CheckVaultExists():Promise<main.Response>;

export function CreateVault(arg1:string):Promise<main.Response>;

export function DeleteFile(arg1:string):Promise<main.Response>;

export function DeleteNote(arg1:string):Promise<main.Response>;

export function DisableTOTP():Promise<main.Response>;

export function EnableTOTP(arg1:string,arg2:string):Promise<main.Response>;

export function ExportBackup(arg1:string):Promise<main.Response>;

export function ExportFile(arg1:string):Promise<main.Response>;

export function ExportFileForced(arg1:string):Promise<main.Response>;

export function ExtractFromImage():Promise<main.Response>;

export function GetFileTamperDetails(arg1:string):Promise<main.Response>;

export function GetFiles():Promise<main.Response>;

export function GetNote(arg1:string):Promise<main.Response>;

export function GetNotes():Promise<main.Response>;

export function GetVaultInfo():Promise<main.Response>;

export function HideInImage(arg1:string,arg2:string):Promise<main.Response>;

export function ImportBackup(arg1:string):Promise<main.Response>;

export function IsReadOnly():Promise<main.Response>;

export function IsTOTPEnabled():Promise<main.Response>;

export function IsUnlocked():Promise<main.Response>;

export function LockVault():Promise<main.Response>;

export function PreviewHideInImage(arg1:string,arg2:string):Promise<main.Response>;

export function ResetPasswordWithRecovery(arg1:string,arg2:string):Promise<main.Response>;

export function RestoreFromBackup(arg1:string,arg2:string):Promise<main.Response>;

export function SearchNotes(arg1:string):Promise<main.Response>;

export function SelectImage():Promise<main.Response>;

export function SetupTOTP():Promise<main.Response>;

export function UnlockVault(arg1:string,arg2:string):Promise<main.Response>;

export function UnlockVaultReadOnly(arg1:string):Promise<main.Response>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.Response>;

export function ValidateRecoveryKey(arg1:string):Promise<main.Response>;

export function VerifyFile(arg1:string):Promise<main.Response>;
